### ISSUE TITLE
Backend Project Build Fails

### ISSUE THREAD

**Issue by vangelis-b** [DevExpress-Examples/dashboard-react-app#2]
The project within the asp-net-core-server folder fails to build with the following error message. The package `DevExpress.AspNetCore.Dashboard` doesn't exist in nugget.org. Any thoughts of what I need to do? Thanks

```
asp-net-core-server % dotnet run
/Users/vbouzoukas002/Downloads/dashboard-react-app-20.2.1-/asp-net-core-server/AspNetCoreDashboardBackend.csproj : error NU1101: Unable to find package DevExpress.AspNetCore.Dashboard. No packages exist with this id in source(s): nuget.org

The build failed. Fix the build errors and run again.
```

**Comment by Stason4eg** [comment]
Hello,

The DevExpress.AspNetCore.Dashboard package is not found, because the NuGet feed is not set for this example. You need to set your NuGet API key before running an application. I recommend you refer to this page for more details: [https://docs.devexpress.com/GeneralInformation/115912/installation/install-devexpress-controls-using-nuget-packages](https://docs.devexpress.com/GeneralInformation/115912/installation/install-devexpress-controls-using-nuget-packages)
